### ISSUE TITLE
Some issues about the overtake datasets.

### ISSUE THREAD

**Issue by SunHaoOne** [JeffTheHacker/ContingenciesFromObservations#3]
Hello,
Thanks for you excellent code here and I am very interested in the overtake senarios. After downloading you datasets, I found there is no test or valid dataset and only train datasets here. And I have some questions as follows:
### How to generate the overtake dataset?
I cannot find the code about how to generate the overtake dataset, but I get the code [Behaviors](https://github.com/JeffTheHacker/ContingenciesFromObservations/blob/main/Experiment/Overtake_Scenario/behaviors.py) here. I guess the datasets is generate from this **Behavior Agent**. Please let me know if I am wrong. Thanks!

**Comment by JeffTheHacker** [comment]
Hi, the datasets are indeed generated from the behavior agent. Details about how to generate the dataset are contained in the readme. Specifically, you can run 
```
python scenario_runner.py \
--enable-collecting \
--scenario 1 \
--location 0  
```
to specify the scenario that you want to collect data for. For overtaking, scenario will be 1. 
Episode data will be stored to Experiment/Data folder.
Then run:
`python Utils/prepare_data.py`
This will convert the episode data objects into json file per frame, and store them in Data/JSON_output folder.

**Comment by SunHaoOne** [comment]
Hi JeffTheHacker, sorry for the late reply. 
> After runing the `overtake scenario` for about 1500 episode, there is no data saved in the `Data` Folder.

```
Currently at episode 1508
Behavior type for this episode: 4
Currently at episode 1509
Behavior type for this episode: 5
ERROR: failed to destroy actor Traceback (most recent call last):
  File "scenario_runner.py", line 647, in <module>
    main()
  File "scenario_runner.py", line 624, in main
    runner.start()
  File "scenario_runner.py", line 129, in start
    self.world.tick()
RuntimeError: time-out of 10000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:2000
finished processing episode 0
Killed
```
> There is only an empty file `Episode_0`here, and also cannot generated the json file.

Finally I found this error is caused by the abrupted carla simulator, and after `ctrl+c`, the data can rightly generated. And how many episode is needed for training?
